apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: infrastructure
spec:
  ports:
  - port: 2181
    name: client
  selector:
    data: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-internal
  namespace: infrastructure
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  selector:
    data: zookeeper
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zookeeper-pdb
  namespace: infrastructure
spec:
  selector:
    matchLabels:
      data: zookeeper
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: infrastructure
spec:
  serviceName: zookeeper-internal
  replicas: 5
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      data: zookeeper
  template:
    metadata:
      labels:
        data: zookeeper
    spec:
      securityContext:
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "data"
                    operator: In
                    values:
                    - zookeeper
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: zookeeper
        imagePullPolicy: Always
        image: warrenhuang/zookeeper:3.6.2
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        resources:
          requests:
            cpu: 1000m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 512Mi          
        env:
          - name: ZK_SERVER_HEAP
            value: "256"
          - name: ZK_REPLICAS
            value: "5"
          - name: ZK_AUTOPURGE_PURGEINTERVAL
            value: "1"
          - name: ZK_AUTOPURGE_SNAPRETAINCOUNT
            value: "3"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "healthcheck.sh 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "healthcheck.sh 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: zookeeper-data
          mountPath: /data
        - name: zookeeper-datalog
          mountPath: /datalog
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 512Mi
  - metadata:
      name: zookeeper-datalog
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 512Mi